#!/usr/bin/env perl
# http://adventofcode.com/2017/day/2 <- link to problem

use strict;
use warnings;
use List::Util qw( max min );
use feature qw( say );

use Test::More;

my @test_data = (
    [ 5, 1, 9, 5],
    [ 7, 5, 3],
    [ 2, 4, 6, 8]
    );

is( checksum( \@test_data ), 18 );

done_testing();


sub checksum {
    my $input = shift;
    my @input = @{ $input };
    my $checksum;
    foreach (@input){
        my $max = max@{$_};
        my $min = min@{$_};
        $checksum += $max - $min;
    }
    return $checksum;
}

my @data;

my $filename = 'data_day2';
if (open(my $fh, '<:encoding(UTF-8)', $filename)){
    while (my $row = <$fh>){
        my @row_array;
        chomp $row;
        @row_array = split ' ', $row;
        push @data, \@row_array;
    }
}
else {
    warn "Could not open file '$filename' $!";
}

say "Puzzle answer is: ", checksum(\@data);
